Make KeyPairName parameter optional
aws-quickstart/quickstart-linux-bastion pull request #139
Opened 2021-11-15 15:08 UTC by kolomied

*Issue #, if available:*

*Description of changes:*
As Sessions Manager is already supported, key pair may be an optional parameter.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-11-17 17:53 UTC, andrew-glenn requested changes
The `UseKeyPair` conditional should eval to "If the `KeyPairName` parameter is not the default value"

2021-11-17 17:53 UTC, andrew-glenn commented on templates/linux-bastion.template
> +    - ''
```suggestion
  UseKeyPair: !Not
    - !Equals
      - !Ref KeyPairName
      - ''  
```

2021-11-19 16:17 UTC, kolomied commented on templates/linux-bastion.template
> +    - ''
Thank you @andrew-glenn, addressed

2021-12-01 16:34 UTC, andrew-glenn approved these changes

2021-12-01 16:34 UTC, merged